
INSERT INTO bars(id, name, slug, category_id, city, province, address, phones, lng, lat, price, color, created, description) VALUES
(1,'BBC Andino','bbc-andino',1,'Bogotá','Cundinamarca','Cra. 12 No. 83-33','(1)7429292 ext. 311',4.667483, -74.053242, 22000.00, 'CYAN', NOW(),
	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit lorem vitae egestas facilisis. Cras quis congue nunc. Aliquam dapibus placerat lorem, ut porta nisl euismod vel. Nulla volutpat erat urna, tincidunt eleifend lectus tristique in. Proin imperdiet cursus sagittis. Etiam molestie hendrerit lectus quis fermentum. Fusce varius massa augue, sed sagittis lectus faucibus et. Suspendisse posuere euismod nisl id convallis. Proin vel diam justo. Aliquam fringilla pretium quam, eu commodo dolor placerat vel. Donec egestas mauris quis finibus mattis. Phasellus aliquet lectus et eleifend gravida. Sed luctus lacus mi, vitae sagittis velit euismod a. Nam blandit fringilla massa, in sollicitudin justo scelerisque id. Nunc pulvinar ac ipsum a cursus.'),
(2,'BBC Cedritos','bbc-cedritos',1,'Bogotá','Cundinamarca','Av. 19 No. 139 – 07','(1)7429292 ext. 315',4.723106, -74.046335, 22000.00, 'CYAN', NOW(),
	'In sit amet facilisis elit. Mauris a lorem tellus. Donec placerat justo ut nulla luctus, vel sodales ante fringilla. Mauris nec nunc vitae orci scelerisque consequat ac a nibh. Cras ullamcorper, velit ut volutpat lacinia, quam odio gravida mauris, non finibus nulla purus at magna. Nulla lorem tortor, varius et feugiat a, lacinia et eros. Nullam rhoncus lorem non laoreet posuere. Aenean id massa faucibus, tempus lectus non, porta justo. Integer id nunc egestas, euismod est a, ultricies nulla. Donec et turpis lorem.'),
(3,'BBC Salitre','bcc-salitre',1,'Bogotá','Cundinamarca','Av. Cll. 26 No. 68B – 85','(1)7429292 ext. 318',4.655441, -74.106444, 22000.00, 'CYAN', NOW(),
	'Nam eget turpis mollis, vulputate elit et, blandit elit. Ut pharetra sollicitudin venenatis. Fusce ut tincidunt nisi, quis cursus nisl. Fusce bibendum non eros nec malesuada. Vivamus aliquam, nibh vitae vehicula pulvinar, ligula erat eleifend nisi, nec scelerisque elit lorem et purus. Fusce eget nulla neque. Sed ultrices blandit dignissim. Proin at malesuada massa, nec efficitur eros. Pellentesque mi tortor, pretium ac nibh nec, sagittis ultrices magna.'),
(4,'Joshua Suramericana Salitre','joshua-salitre',1,'Bogotá','Cundinamarca','Calle 25B #68B-26 Torre Suramericana Local 108','4272944',4.655589, -74.106410, 25000.00, 'BROWN', NOW(),
	'Suspendisse placerat faucibus arcu, ut aliquam metus pulvinar in. Vestibulum ut tellus vitae ligula mollis consectetur eget vitae nunc. Mauris tincidunt auctor elit, sed ornare metus efficitur in. In interdum congue ipsum vitae elementum. Duis ut quam in lectus varius lacinia. Sed eget turpis ac risus tempor ultrices. Nam turpis nisl, auctor posuere malesuada sed, rhoncus id mauris. Mauris scelerisque ornare ligula sed mollis. Mauris at neque quis libero vehicula laoreet. Fusce suscipit eu massa eu suscipit. Phasellus et ante sit amet nisl tincidunt commodo eget eget nibh. Vestibulum dignissim justo lorem, sit amet dignissim nunc auctor quis.'),
(5,'Joshua Centro Mayor','joshua-centro-mayor',1,'Bogotá','Cundinamarca','Centro Mayor Centro Comercial Local 3055', '7383072', 4.593426, -74.124627, 25000.00, 'BROWN', NOW(),
	'Ut feugiat sem nec odio dictum, in faucibus nibh rutrum. Nam placerat felis ut magna semper accumsan. Cras orci tellus, dictum eu sodales ut, finibus at nunc. Donec suscipit ante ipsum, at tristique turpis suscipit non. Sed est diam, fermentum id arcu eget, aliquet suscipit odio. Nulla eget fermentum lorem, nec faucibus libero. Aliquam erat volutpat. Aenean a odio eget risus laoreet tempor vitae at orci. Etiam sagittis blandit tellus, eu euismod lectus luctus ac. In metus est, dignissim ac risus nec, rutrum consectetur nunc. Curabitur maximus purus non mauris dictum, at mollis purus mollis. Sed nec mauris ut purus ullamcorper maximus vel quis ligula. Vivamus consectetur finibus magna, eu ullamcorper sem. Vestibulum ac libero et sem varius vestibulum. Integer sodales scelerisque elit, sed luctus massa varius a. Nulla sollicitudin scelerisque consequat.');
