DROP TABLE IF EXISTS atlas_users;

CREATE TABLE atlas_users (
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(32) NOT NULL UNIQUE,
	email VARCHAR(128) NOT NULL UNIQUE,
	password CHAR(40) NOT NULL,
	fname VARCHAR(64) NOT NULL,
	lname VARCHAR(64) NOT NULL,
	role ENUM('ADMIN','USER') NOT NULL DEFAULT 'USER'
)CHARSET utf8 COLLATE utf8_general_ci;

