
DROP TABLE IF EXISTS bars_genres;

CREATE TABLE bars_genres(
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	slug VARCHAR(32) NOT NULL UNIQUE
)CHARSET utf8 COLLATE utf8_general_ci;

