
DROP TABLE IF EXISTS bars_countries;

CREATE TABLE bars_countries (
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	slug VARCHAR(32) NOT NULL UNIQUE,
	iso2 CHAR(2) NOT NULL UNIQUE,
	iso3 CHAR(3) NOT NULL UNIQUE
)CHARSET utf8 COLLATE utf8_general_ci;

