
DROP TABLE IF EXISTS bars_provinces;

CREATE TABLE bars_provinces (
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	slug VARCHAR(32) NOT NULL UNIQUE,
	country_id BIGINT NOT NULL,
	iso2 CHAR(6) NOT NULL UNIQUE
)CHARSET utf8 COLLATE utf8_general_ci;

