
DROP TABLE IF EXISTS bars_cities;

CREATE TABLE bars_cities (
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	slug VARCHAR(32) NOT NULL UNIQUE,
	province_id BIGINT NOT NULL
)CHARSET utf8 COLLATE utf8_general_ci;

