
DROP TABLE IF EXISTS bars_zones;

CREATE TABLE bars_zones (
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	slug VARCHAR(32) NOT NULL UNIQUE,
	city_id BIGINT NOT NULL,
	lat         DECIMAL(17,14) NOT NULL,
	lng         DECIMAL(17,14) NOT NULL
)CHARSET utf8 COLLATE utf8_general_ci;

