DROP TABLE IF EXISTS places;

CREATE TABLE places (
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	description MEDIUMTEXT NOT NULL,
	lng DECIMAL(17,14) NOT NULL,
	lat DECIMAL(17,14) NOT NULL,
	enabled ENUM('TRUE','FALSE') NOT NULL DEFAULT 'TRUE',
	created DATETIME
)CHARSET utf8 COLLATE utf8_general_ci;

