
DROP TABLE IF EXISTS tokens;

CREATE TABLE tokens (
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	token CHAR(32) NOT NULL UNIQUE,
	created DATETIME NOT NULL,
	expires DATETIME NOT NULL
)CHARSET utf8 COLLATE utf8_general_ci;

