
DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(32) NOT NULL UNIQUE,
	email VARCHAR(128) NOT NULL UNIQUE,
	password CHAR(64) NOT NULL,
	salt  CHAR(40) NOT NULL,
	fname VARCHAR(64) NOT NULL,
	lname VARCHAR(64) NOT NULL,
	role ENUM('ADMIN','USER') NOT NULL DEFAULT 'USER',
	created DATETIME NOT NULL,
	updated DATETIME NULL
)CHARSET utf8 COLLATE utf8_general_ci;

